### ISSUE TITLE
Execute the documentation strategy

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/website#158]
# Purpose
The purpose of this issue is to execute the Documentation strategy defined in issue #245 .

# Scope
See issue #245 .

# Objectives
See issue #245 .

# Repository
All the changes will be implemented in the new website repo: https://github.com/json-schema-org/website

<a id="release-plan"></a>
# Plan
 🏁 **[Release 1](https://github.com/json-schema-org/website/milestone/1)** 
  - [x] overview\What is JSON schema [PR 47](https://github.com/json-schema-org/website/pull/47)
  - [x] learn\Getting started [PR 46](https://github.com/json-schema-org/website/pull/46)

 🏁 **[Release 2](https://github.com/json-schema-org/website/milestone/2)**
  - [x] Examples: Improve structure and consistency.
    - [x] Miscellaneous Examples page. #48 
    - [x] Other Examples page. #62 
  - [x] json-schema-org/community#300 
  - [x] learn\Glossary (https://json-schema.org/learn/glossary.html)
  - [x] #126 
  - [x] #127 
  
 🏁 **Release 3**
  - [x] #421 
  - [x] #190 
  - [x] #280
  - [x] #440 
  - [x] #426   
 

 🏁 **Release TBD**
  - [x] #282 
  - [x] #243 
  - [x] #634

  <a id="release4"></a>
 🏁 **Release 4**
  - [x] #791 

  <a id="release5"></a>
 🏁 **Release 5**
 Rebuild the Reference docs
  - [x] Replace Understanding JSON Schema
  - [x] https://github.com/json-schema-org/website/issues/110

 🏁 **Release 6**
  - [ ] #180
  - [x] #960
  - [ ] #954 
  - [x] #950 
  - [ ] #971
  - [ ] #970

 🏁 **Release 7**
  - [x] #181
  - [x] #801
  - [ ] overview\Vision (New)
  - [ ] overview\Release and Versioning (New)

 🏁 **Release 8**
  - [ ] Guide for Bowtie
  - [ ] Guide for Test Suite
  
 🏁 **Release 9**
  - [ ] Guide of use of JSON Schema at scale.

 🏁 **Release 10**
  - [ ] Metaschemas documentation
  - [ ] https://github.com/json-schema-org/website/issues/141 
  
# Success Metrics
See issue #245 .

# Risks
See issue #245 .

# Governance
We'll use milestones to group releases.

This is the group of people working in this project:
 - @benjagm 
 - @mjgutermuth
 - @aku1310

**Comment by meny3437-blip** [comment]
> # Purpose
> 
> The purpose of this issue is to execute the Documentation strategy defined in issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Scope
> 
> See issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Objectives
> 
> See issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Repository
> 
> All the changes will be implemented in the new website repo: https://github.com/json-schema-org/website
> 
> # Plan
> 
> 🏁 **[Release 1](https://github.com/json-schema-org/website/milestone/1)**
> 
> * [x]  overview\What is JSON schema [PR 47](https://github.com/json-schema-org/website/pull/47)[x]  learn\Getting started [PR 46](https://github.com/json-schema-org/website/pull/46)
> 
> 🏁 **[Release 2](https://github.com/json-schema-org/website/milestone/2)**
> 
> * * [x]  Examples: Improve structure and consistency.
>     
>     * [x]  Miscellaneous Examples page. [[Docs] Updated 'Miscellaneous Examples' Section #48](https://github.com/json-schema-org/website/pull/48)* [x]  Other Examples page. [[Docs] Updated Examples Section #62](https://github.com/json-schema-org/website/pull/62)[x]  [Website Analytics  community#300](https://github.com/json-schema-org/community/issues/300)[x]  learn\Glossary (https://json-schema.org/learn/glossary.html)[x]  [Links to similar technologies #126](https://github.com/json-schema-org/website/issues/126)[x]  [add links to openapi website #127](https://github.com/json-schema-org/website/issues/127)
> 
> 🏁 **Release 3**
> 
> * [x]  [[📑 Docs]: Lets create a welcome page for the docs section #421](https://github.com/json-schema-org/website/issues/421)[x]  [cookbook page, with solutions to frequently asked questions #190](https://github.com/json-schema-org/website/issues/190)[x]  [Create a new page for Community inside the Overview Section of the Docs. #280](https://github.com/json-schema-org/website/issues/280)[x]  [✨ Enhancement: Page in overview section to show Case Studies #440](https://github.com/json-schema-org/website/issues/440)[x]  [✨ Enhancement: Create the use cases page #426](https://github.com/json-schema-org/website/issues/426)
> 
> 🏁 **Release TBD**
> 
> * [x]  [Add a new section in the Docs for other JSON Schema resources #282](https://github.com/json-schema-org/website/issues/282)[x]  [Add a newsletter subscribe form to the Landing Page #243](https://github.com/json-schema-org/website/issues/243)[x]  [✨ Enhancement: Newsletter landing page #634](https://github.com/json-schema-org/website/issues/634)
> 
> 🏁 **Release 4**
> 
> * [x]  [[📝 Docs]:  Implement the Spec page restructuring (Docs Website) #791](https://github.com/json-schema-org/website/issues/791)
> 
> 🏁 **Release 5** Rebuild the Reference docs
> 
> * [x]  Replace Understanding JSON Schema[x]  [Review UJS conventions / language-specific notes #110](https://github.com/json-schema-org/website/issues/110)
> 
> 🏁 **Release 6**
> 
> * [x]  [Create a guide for implementers #180](https://github.com/json-schema-org/website/issues/180)[x]  [Undocumented features/keywords on the website is reduced to zero. #960](https://github.com/json-schema-org/website/issues/960)[ ]  [[📝 Docs]: Create guide "How to validate data against a JSON schema"  #954](https://github.com/json-schema-org/website/issues/954)[x]  [[📝 Docs]: Create guide "How to structure a complex JSON schema" #950](https://github.com/json-schema-org/website/issues/950)[ ]  [Creating a dedicated JSON Hyperschema page. #971](https://github.com/json-schema-org/website/issues/971)[ ]  [Creating a Migration docs for all drafts. #970](https://github.com/json-schema-org/website/issues/970)
> 
> 🏁 **Release 7**
> 
> * [x]  [Roadmap page for the Overview section #181](https://github.com/json-schema-org/website/issues/181)[x]  [Implement breadcrumbs. #801](https://github.com/json-schema-org/website/issues/801)[ ]  overview\Vision (New)[ ]  overview\Release and Versioning (New)
> 
> 🏁 **Release 8**
> 
> * [ ]  Guide for Bowtie[ ]  Guide for Test Suite
> 
> 🏁 **Release 9**
> 
> * [ ]  Guide of use of JSON Schema at scale.
> 
> 🏁 **Release 10**
> 
> * [ ]  Metaschemas documentation[ ]  [Explain meta-schema status and support #141](https://github.com/json-schema-org/website/issues/141)
> 
> # Success Metrics
> 
> See issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Risks
> 
> See issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Governance
> 
> We'll use milestones to group releases.
> 
> This is the group of people working in this project:
> 
> * [@benjagm](https://github.com/benjagm)
> * [@mjgutermuth](https://github.com/mjgutermuth)
> * [@aku1310](https://github.com/aku1310)



> # Purpose
> 
> The purpose of this issue is to execute the Documentation strategy defined in issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Scope
> 
> See issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Objectives
> 
> See issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Repository
> 
> All the changes will be implemented in the new website repo: https://github.com/json-schema-org/website
> 
> # Plan
> 
> 🏁 **[Release 1](https://github.com/json-schema-org/website/milestone/1)**
> 
> * [x]  overview\What is JSON schema [PR 47](https://github.com/json-schema-org/website/pull/47)[x]  learn\Getting started [PR 46](https://github.com/json-schema-org/website/pull/46)
> 
> 🏁 **[Release 2](https://github.com/json-schema-org/website/milestone/2)**
> 
> * * [x]  Examples: Improve structure and consistency.
>     
>     * [x]  Miscellaneous Examples page. [[Docs] Updated 'Miscellaneous Examples' Section #48](https://github.com/json-schema-org/website/pull/48)* [x]  Other Examples page. [[Docs] Updated Examples Section #62](https://github.com/json-schema-org/website/pull/62)[x]  [Website Analytics  community#300](https://github.com/json-schema-org/community/issues/300)[x]  learn\Glossary (https://json-schema.org/learn/glossary.html)[x]  [Links to similar technologies #126](https://github.com/json-schema-org/website/issues/126)[x]  [add links to openapi website #127](https://github.com/json-schema-org/website/issues/127)
> 
> 🏁 **Release 3**
> 
> * [x]  [[📑 Docs]: Lets create a welcome page for the docs section #421](https://github.com/json-schema-org/website/issues/421)[x]  [cookbook page, with solutions to frequently asked questions #190](https://github.com/json-schema-org/website/issues/190)[x]  [Create a new page for Community inside the Overview Section of the Docs. #280](https://github.com/json-schema-org/website/issues/280)[x]  [✨ Enhancement: Page in overview section to show Case Studies #440](https://github.com/json-schema-org/website/issues/440)[x]  [✨ Enhancement: Create the use cases page #426](https://github.com/json-schema-org/website/issues/426)
> 
> 🏁 **Release TBD**
> 
> * [x]  [Add a new section in the Docs for other JSON Schema resources #282](https://github.com/json-schema-org/website/issues/282)[x]  [Add a newsletter subscribe form to the Landing Page #243](https://github.com/json-schema-org/website/issues/243)[x]  [✨ Enhancement: Newsletter landing page #634](https://github.com/json-schema-org/website/issues/634)
> 
> 🏁 **Release 4**
> 
> * [x]  [[📝 Docs]:  Implement the Spec page restructuring (Docs Website) #791](https://github.com/json-schema-org/website/issues/791)
> 
> 🏁 **Release 5** Rebuild the Reference docs
> 
> * [x]  Replace Understanding JSON Schema[x]  [Review UJS conventions / language-specific notes #110](https://github.com/json-schema-org/website/issues/110)
> 
> 🏁 **Release 6**
> 
> * [x]  [Create a guide for implementers #180](https://github.com/json-schema-org/website/issues/180)[x]  [Undocumented features/keywords on the website is reduced to zero. #960](https://github.com/json-schema-org/website/issues/960)[ ]  [[📝 Docs]: Create guide "How to validate data against a JSON schema"  #954](https://github.com/json-schema-org/website/issues/954)[x]  [[📝 Docs]: Create guide "How to structure a complex JSON schema" #950](https://github.com/json-schema-org/website/issues/950)[ ]  [Creating a dedicated JSON Hyperschema page. #971](https://github.com/json-schema-org/website/issues/971)[ ]  [Creating a Migration docs for all drafts. #970](https://github.com/json-schema-org/website/issues/970)
> 
> 🏁 **Release 7**
> 
> * [x]  [Roadmap page for the Overview section #181](https://github.com/json-schema-org/website/issues/181)[x]  [Implement breadcrumbs. #801](https://github.com/json-schema-org/website/issues/801)[ ]  overview\Vision (New)[ ]  overview\Release and Versioning (New)
> 
> 🏁 **Release 8**
> 
> * [ ]  Guide for Bowtie[ ]  Guide for Test Suite
> 
> 🏁 **Release 9**
> 
> * [ ]  Guide of use of JSON Schema at scale.
> 
> 🏁 **Release 10**
> 
> * [ ]  Metaschemas documentation[ ]  [Explain meta-schema status and support #141](https://github.com/json-schema-org/website/issues/141)
> 
> # Success Metrics
> 
> See issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Risks
> 
> See issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Governance
> 
> We'll use milestones to group releases.
> 
> This is the group of people working in this project:
> 
> * [@benjagm](https://github.com/benjagm)
> * [@mjgutermuth](https://github.com/mjgutermuth)
> * [@aku1310](https://github.com/aku1310)



> # Purpose
> 
> The purpose of this issue is to execute the Documentation strategy defined in issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Scope
> 
> See issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Objectives
> 
> See issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Repository
> 
> All the changes will be implemented in the new website repo: https://github.com/json-schema-org/website
> 
> # Plan
> 
> 🏁 **[Release 1](https://github.com/json-schema-org/website/milestone/1)**
> 
> * [x]  overview\What is JSON schema [PR 47](https://github.com/json-schema-org/website/pull/47)[x]  learn\Getting started [PR 46](https://github.com/json-schema-org/website/pull/46)
> 
> 🏁 **[Release 2](https://github.com/json-schema-org/website/milestone/2)**
> 
> * * [x]  Examples: Improve structure and consistency.
>     
>     * [x]  Miscellaneous Examples page. [[Docs] Updated 'Miscellaneous Examples' Section #48](https://github.com/json-schema-org/website/pull/48)* [x]  Other Examples page. [[Docs] Updated Examples Section #62](https://github.com/json-schema-org/website/pull/62)[x]  [Website Analytics  community#300](https://github.com/json-schema-org/community/issues/300)[x]  learn\Glossary (https://json-schema.org/learn/glossary.html)[x]  [Links to similar technologies #126](https://github.com/json-schema-org/website/issues/126)[x]  [add links to openapi website #127](https://github.com/json-schema-org/website/issues/127)
> 
> 🏁 **Release 3**
> 
> * [x]  [[📑 Docs]: Lets create a welcome page for the docs section #421](https://github.com/json-schema-org/website/issues/421)[x]  [cookbook page, with solutions to frequently asked questions #190](https://github.com/json-schema-org/website/issues/190)[x]  [Create a new page for Community inside the Overview Section of the Docs. #280](https://github.com/json-schema-org/website/issues/280)[x]  [✨ Enhancement: Page in overview section to show Case Studies #440](https://github.com/json-schema-org/website/issues/440)[x]  [✨ Enhancement: Create the use cases page #426](https://github.com/json-schema-org/website/issues/426)
> 
> 🏁 **Release TBD**
> 
> * [x]  [Add a new section in the Docs for other JSON Schema resources #282](https://github.com/json-schema-org/website/issues/282)[x]  [Add a newsletter subscribe form to the Landing Page #243](https://github.com/json-schema-org/website/issues/243)[x]  [✨ Enhancement: Newsletter landing page #634](https://github.com/json-schema-org/website/issues/634)
> 
> 🏁 **Release 4**
> 
> * [x]  [[📝 Docs]:  Implement the Spec page restructuring (Docs Website) #791](https://github.com/json-schema-org/website/issues/791)
> 
> 🏁 **Release 5** Rebuild the Reference docs
> 
> * [x]  Replace Understanding JSON Schema[x]  [Review UJS conventions / language-specific notes #110](https://github.com/json-schema-org/website/issues/110)
> 
> 🏁 **Release 6**
> 
> * [x]  [Create a guide for implementers #180](https://github.com/json-schema-org/website/issues/180)[x]  [Undocumented features/keywords on the website is reduced to zero. #960](https://github.com/json-schema-org/website/issues/960)[ ]  [[📝 Docs]: Create guide "How to validate data against a JSON schema"  #954](https://github.com/json-schema-org/website/issues/954)[x]  [[📝 Docs]: Create guide "How to structure a complex JSON schema" #950](https://github.com/json-schema-org/website/issues/950)[ ]  [Creating a dedicated JSON Hyperschema page. #971](https://github.com/json-schema-org/website/issues/971)[ ]  [Creating a Migration docs for all drafts. #970](https://github.com/json-schema-org/website/issues/970)
> 
> 🏁 **Release 7**
> 
> * [x]  [Roadmap page for the Overview section #181](https://github.com/json-schema-org/website/issues/181)[x]  [Implement breadcrumbs. #801](https://github.com/json-schema-org/website/issues/801)[ ]  overview\Vision (New)[ ]  overview\Release and Versioning (New)
> 
> 🏁 **Release 8**
> 
> * [ ]  Guide for Bowtie[ ]  Guide for Test Suite
> 
> 🏁 **Release 9**
> 
> * [ ]  Guide of use of JSON Schema at scale.
> 
> 🏁 **Release 10**
> 
> * [ ]  Metaschemas documentation[ ]  [Explain meta-schema status and support #141](https://github.com/json-schema-org/website/issues/141)
> 
> # Success Metrics
> 
> See issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Risks
> 
> See issue [#245](https://github.com/json-schema-org/website/issues/245) .
> 
> # Governance
> 
> We'll use milestones to group releases.
> 
> This is the group of people working in this project:
> 
> * [@benjagm](https://github.com/benjagm)
> * [@mjgutermuth](https://github.com/mjgutermuth)
> * [@aku1310](https://github.com/aku1310)
