### ISSUE TITLE
Create a JSON Schema Glossary Page or Site

### ISSUE THREAD

**Issue by Julian** [json-schema-org/website#266]
It'd be nice if we had a glossary of terms -- a page, in not very technical jargon, which explains common terminology used by us in conversation, and which could be linked to by other pages or people in order to answer questions like "what is a vocabulary" in a succinct way.

Here are two examples of glossaries I've contributed to or used heavily which may be decent examples of the concept:

* [The Python glossary](https://docs.python.org/3/glossary.html)
* [The Lean glossary](https://leanprover-community.github.io/glossary.html#widget)

EDIT: The page has been published at https://json-schema.org/learn/glossary.html

To help, just grab any of the entries below which don't already exist on the page, and share that you're working on them!

---

List of Terms to Define

- [x] dialect json-schema-org/json-schema-org.github.io#484
- [x] instance json-schema-org/json-schema-org.github.io#462
- [x] vocabulary json-schema-org/json-schema-org.github.io#484
- [x] schema json-schema-org/json-schema-org.github.io#462
- [x] meta-schema json-schema-org/json-schema-org.github.io#469
- [x] keyword json-schema-org/json-schema-org.github.io#469
- [ ] hyper-schema
- [x] draft json-schema-org/json-schema-org.github.io#461
- [ ] ref
- [ ] annotation
- [ ] validation
- [ ] validation result
- [ ] annotation (keyword)
- [ ] validation (keyword)
- [ ] assertion (keyword)
- [ ] in-place application
- [ ] child application
- [x] subschema json-schema-org/json-schema-org.github.io#520
- [ ] resource / schema resource
- [ ] compound schema resource
- [ ] anchor
- [x] JSON json-schema-org/json-schema-org.github.io#521
- [ ] JSON pointer
- [ ] relative JSON pointer

**Comment by bhavukkalra** [comment]
In the process of creating a drafts for `annotation` and `validation`. Will send over for review once ready

**Comment by vickywane** [comment]
@benjagm I'd love to take up `anchor` and `ref` and submit a PR for them.

**Comment by benjagm** [comment]
> @benjagm I'd love to take up `anchor` and `ref` and submit a PR for them.

Thanks a lot @vickywane ! Please go ahead

**Comment by bhavukkalra** [comment]
Just created PR #668. To add the sections of `annotation` and `annotation (keyword)`. I tried to these two attributes in a single PR as these are closely related and one references the other.

**Comment by Temidayo32** [comment]
I will be submitting PR for `resource / schema resource` and `compound schema resource`.

**Comment by starlightknown** [comment]
Hi can I take up `JSON pointer` and
 `validation result`?

**Comment by benjagm** [comment]
> I will be submitting PR for `resource / schema resource` and `compound schema resource`.

Thanks a lot. Please go ahead.

**Comment by benjagm** [comment]
This is a long term issue. We'll keep it open.

**Comment by umarbshehu** [comment]
@benjagm I would like to work on "relative JSON pointer."

**Comment by umarbshehu** [comment]
@benjagm I requested to work on `relative JSON pointer`, but you removed my post without giving a reason.

I want to know why my request was removed from JSON Schema Docs.

**Comment by benjagm** [comment]
Thanks a lot for working on this @umarbshehu. My advice is to start with the available definition of JSON Pointer and do a research in the JSON Schema specification to understand the relative JSON pointer and provide your description avoiding repeating the same wording used in the spec.

**Comment by neerja-1984** [comment]
@umarbshehu @benjagm from the above conversation ive understood it is a long term issue and needs work. I wish to contribute to it. please let me know how much work is done here so I can help !

**Comment by umarbshehu** [comment]
Hi,

I intended to work on it, but I didn't.
I worked on something else.

You can go ahead and add your contribution.

Best WIshes,
Umar Shehu

**Comment by Shristibot** [comment]
Hi everyone,

I’d like to contribute to this long‑term glossary effort. I’ve reviewed the existing glossary page at 
https://json-schema.org/learn/glossary and the terms list in this issue.
​

I’d be happy to take on the following term(s): relative JSON pointer (and possibly another unclaimed term, if you recommend one). I’ll draft short, non‑implementer‑focused definitions based on the JSON Schema specification and the “Understanding JSON Schema” documentation, avoiding copying spec wording, and then open a PR against pages/learn/glossary.md.
​

Please let me know if you prefer I start with different terms or follow any additional guidelines for glossary contributions.
