### ISSUE TITLE
✨ Enhancement: Data Preparation for Improved Data Model

### ISSUE THREAD

**Issue by DarhkVoyd** [json-schema-org/website#717]
**Description:**
The current data model for the website needs significant improvements to enhance maintainability, completeness, and structure. The existing model primarily contains validators' data for the tooling section, while other data is hardcoded into the markdown files. This issue aims to clean unused and outdated fields, redesign the data model to consolidate all relevant data into a single file, and add maintainer details for future community events.

#### Tasks:

- [x] Review and Cleanup Existing Data Model
- [x] Consolidate Data into a Single File
- [x] Add Maintainer Details for Community Events

**Comment by benjagm** [comment]
Hi DV. Con you please add the issue documentation? I think something failed during the creation and the issue description is completely empty.
